services:
  fishcatcher-site:
    build: .
    container_name: fishcatcher-site
    restart: unless-stopped
    ports:
      - "127.0.0.1:8419:80"
    networks:
      - fishcatcher

networks:
  fishcatcher:
    name: fishcatcher
