// Stamps dist/chrome and dist/firefox from the shared src/ tree.
// src/manifest.json is the Chromium source of truth; the Firefox variant is derived.
import { cpSync, rmSync, readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
// English only for now; src/_locales/ka stays in the repo (a test enforces key parity).
const SHIPPED_LOCALES = ['en'];
const src = join(root, 'src');
const dist = join(root, 'dist');

export function toFirefoxManifest(m) {
  const f = structuredClone(m);
  delete f.side_panel;
  // Firefox keeps the toolbar popup (Chromium opens the side panel on click instead).
  f.action = { ...f.action, default_popup: 'popup/popup.html' };
  if (f.background?.service_worker) {
    f.background = { scripts: [f.background.service_worker] };
  }
  f.permissions = (f.permissions ?? []).filter((p) => p !== 'sidePanel');
  f.sidebar_action = {
    default_panel: 'panel/panel.html',
    default_title: '__MSG_appName__',
    open_at_install: false
  };
  f.browser_specific_settings = {
    gecko: {
      id: 'fishcatcher@keepitlocal.app',
      // 128: before Firefox 127, MV3 content-script host permissions were not
      // granted at install, so the page probe silently never ran.
      strict_min_version: '128.0',
      // Required by AMO for new submissions since Nov 2025. Nothing leaves the
      // browser by default; the opt-in RDAP / Safe Browsing lookups send the
      // visited domain or URL to a third party only after the user turns them on.
      data_collection_permissions: { required: ['none'], optional: ['websiteActivity'] }
    }
  };
  return f;
}

// Firefox background scripts can't rely on ES modules, so the engine (ESM in
// source, for Node tests) is flattened into one classic script for dist.
// All top-level names across engine modules are unique, so plain concatenation
// in dependency order is safe.
const BACKGROUND_MODULES = [
  'vendor/jsQR.js',
  'engine/punycode.js',
  'engine/psl.js',
  'engine/signals.js',
  'engine/aitm.js',
  'engine/formaction.js',
  'engine/scampacks.js',
  'engine/analyzer.js',
  'engine/links.js',
  'engine/bloom.js',
  'engine/remote.js',
  'engine/rdap.js',
  'engine/ml.js',
  'engine/gsb.js',
  'ui/i18n.js',
  'background.js'
];

const CONTENT_MODULES = [
  'engine/devicecode.js',
  'engine/aitm.js',
  'engine/scampacks.js',
  'ui/i18n.js',
  'probe/probe.js'
];

function bundle(srcDir, modules) {
  const parts = modules.map((rel) =>
    readFileSync(join(srcDir, rel), 'utf8')
      .split('\n')
      .filter((line) => !line.startsWith('import '))
      .map((line) => (line.startsWith('export ') ? line.slice('export '.length) : line))
      .join('\n')
  );
  return `// Generated by scripts/build.mjs — do not edit.\n${parts.join('\n')}\n`;
}

export function bundleBackground(srcDir) {
  return bundle(srcDir, BACKGROUND_MODULES);
}

export function bundleContent(srcDir) {
  return bundle(srcDir, CONTENT_MODULES);
}

function main() {
  rmSync(dist, { recursive: true, force: true });
  const background = bundleBackground(src);
  const content = bundleContent(src);
  for (const target of ['chrome', 'firefox']) {
    const out = join(dist, target);
    cpSync(src, out, { recursive: true });
    for (const locale of readdirSync(join(out, '_locales'))) {
      if (!SHIPPED_LOCALES.includes(locale)) rmSync(join(out, '_locales', locale), { recursive: true });
    }
    writeFileSync(join(out, 'background.js'), background);
    writeFileSync(join(out, 'probe.js'), content);
    const manifest = JSON.parse(readFileSync(join(out, 'manifest.json'), 'utf8'));
    const final = target === 'firefox' ? toFirefoxManifest(manifest) : manifest;
    writeFileSync(join(out, 'manifest.json'), JSON.stringify(final, null, 2) + '\n');
    console.log(`built dist/${target}`);
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
